name: mobievent
description: Plataforma de alquiler de mobiliario para eventos

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.4.0
  cloud_firestore: ^4.2.0
  firebase_auth: ^4.2.0

  # UI
  google_maps_flutter: ^2.2.6
  
  # Para obtener la ubicaciÃ³n actual
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  intl: ^0.18.0
  provider: ^6.0.0

  # Utilidades
  url_launcher: ^6.1.7
  image_picker: ^0.8.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
